/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorClase;
import ec.ups.edu.controlador.ControladorCliente;
import ec.ups.edu.controlador.ControladorEmpleado;
import ec.ups.edu.controlador.ControladorFactura;
import ec.ups.edu.controlador.ControladorProducto;
import ec.ups.edu.modelo.Cliente;
import ec.ups.edu.modelo.DetalleFactura;
import ec.ups.edu.modelo.Empleado;
import ec.ups.edu.modelo.Factura;
import ec.ups.edu.modelo.Producto;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author one
 */
public class VentanaCrearFactura extends javax.swing.JInternalFrame {

    private ControladorCliente controladorCliente;
    private ControladorEmpleado controladorEmpleado;
    private ControladorFactura controladorFactura;
    private ControladorClase controladorClase;
    private ControladorProducto controladorProducto;
    private Factura factura;
    private DetalleFactura detalleFactura;
    private Producto producto;
    private double subtotalv, ivav, totalv,total1v;
    private int c;
    private DefaultTableModel model;
    private Cliente cliente1;
    private Date fecha;
    private SimpleDateFormat formato;
    private Empleado empleado;
    
    public VentanaCrearFactura() {
       
    }

    public VentanaCrearFactura(ControladorCliente controladorCliente, ControladorEmpleado controladorEmpleado, ControladorFactura controladorFactura, ControladorClase controladorClase, ControladorProducto controladorProducto) {
        initComponents();
        this.controladorCliente = controladorCliente;
        this.controladorEmpleado = controladorEmpleado;
        this.controladorFactura = controladorFactura;
        this.controladorClase = controladorClase;
        this.controladorProducto = controladorProducto;
        lblCodigo.setText(String.valueOf(controladorFactura.getCodigo()));
        model = null;
        producto= null;
        totalv = 0;
        subtotalv = 0;
        ivav = 0;
        fecha = new Date();
        formato = new SimpleDateFormat("dd/MM/yyyy");
        lblFecha.setText(formato.format(fecha));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNonbre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblFactura = new javax.swing.JLabel();
        lblFechas = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblCodigos = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFactura = new javax.swing.JTable();
        txtSubTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        jLabel14.setText("jLabel14");

        setClosable(true);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblNombre.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lblCedula.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblCedula.setText("Cedula:");

        lblDireccion.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblDireccion.setText("Direccion:");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblTelefono.setText("Telefono:");

        lblEmpleado.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblEmpleado.setText("Empleado:");

        lblEmail.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblEmail.setText("e-mail:");

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaKeyPressed(evt);
            }
        });

        txtNonbre.setEditable(false);
        txtNonbre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNonbreActionPerformed(evt);
            }
        });

        txtTelefono.setEditable(false);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        txtDireccion.setEditable(false);
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        txtEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpleadoActionPerformed(evt);
            }
        });

        txtEmail.setEditable(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNonbre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCedula)
                        .addComponent(lblTelefono)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblEmpleado)
                    .addComponent(txtNonbre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(lblEmail)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 80, 543, 131);

        lblFactura.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblFactura.setText("FACTURA");
        getContentPane().add(lblFactura);
        lblFactura.setBounds(117, 7, 136, 39);

        lblFechas.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblFechas.setText("Fecha");
        getContentPane().add(lblFechas);
        lblFechas.setBounds(311, 63, 44, 17);
        getContentPane().add(lblFecha);
        lblFecha.setBounds(361, 57, 147, 23);

        lblCodigos.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblCodigos.setText("Codigo");
        getContentPane().add(lblCodigos);
        lblCodigos.setBounds(401, 11, 51, 17);
        getContentPane().add(lblCodigo);
        lblCodigo.setBounds(458, 11, 50, 24);

        tblFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Imagen", "Producto", "Cantidad", "Precio U.", "Precio T."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFactura.setRowHeight(35);
        tblFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblFacturaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblFactura);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 210, 531, 340);

        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtSubTotal);
        txtSubTotal.setBounds(438, 556, 83, 20);

        jLabel8.setText("SubTotal");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(386, 562, 42, 14);
        getContentPane().add(txtIva);
        txtIva.setBounds(438, 582, 83, 20);

        jLabel13.setText("iva");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(414, 585, 14, 14);

        jLabel15.setText("total");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(406, 620, 22, 14);

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal);
        txtTotal.setBounds(438, 619, 83, 20);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/ups/edu/imagenes/Cancelar.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(200, 560, 80, 80);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/ups/edu/imagenes/guardar.jpg"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(100, 560, 80, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtNonbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNonbreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNonbreActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpleadoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyPressed
        String id=txtCedula.getText();
        Set<Cliente> lista = controladorCliente.getLista();
        for(Cliente cliente : lista){
            if(cliente.getCedula().equals(id)){
                cliente1 = cliente;
                txtNonbre.setText(cliente.getNombre());
                txtDireccion.setText(cliente.getDireccion());
                txtEmail.setText(cliente.getEmail());
                txtTelefono.setText(cliente.getTelefono());
            }
        }
        
    }//GEN-LAST:event_txtCedulaKeyPressed

    private void tblFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblFacturaKeyPressed
        int key = evt.getKeyCode();
        if(key == 10){
            int fila= tblFactura.getSelectedRow();
            int columna =tblFactura.getSelectedColumn();
            int codigo=0;
            Object[] datos2 ={"", "", "","0","",""};
            if(columna==0){
                codigo=Integer.parseInt(tblFactura.getValueAt(fila,columna).toString());
                producto = controladorProducto.read(codigo);
                double precio =producto.getCosto();
                double cant = Double.parseDouble(tblFactura.getValueAt(fila, 1).toString());
                model=(DefaultTableModel) tblFactura.getModel();
                model.removeRow(fila);
                total1v= precio* cant;
                Object[] datos ={ codigo,new JLabel(new ImageIcon(producto.getPath())),producto.getNombre(),cant,producto.getCosto(),total1v};
                model.addRow(datos);
                model.addRow(datos2);   
            }else if(columna==1){
                codigo= Integer.parseInt(tblFactura.getValueAt(fila, columna-1).toString());
                double cant= Double.parseDouble(tblFactura.getValueAt(fila, columna).toString());
                model.removeRow(fila);
                model.removeRow(tblFactura.getRowCount()-1);
                total1v= producto.getCosto()*cant;
                Object[] datos ={codigo,new JLabel(new ImageIcon(producto.getPath())),producto.getNombre(),cant,producto.getCosto(),total1v};
                model.addRow(datos);
                model.addRow(datos2);
            }
            subtotalv = total1v+subtotalv;
            ivav= subtotalv*0.12;
            totalv = subtotalv+ivav;
            txtSubTotal.setText(String.valueOf(subtotalv));
            txtIva.setText(String.valueOf(ivav));
            txtTotal.setText(String.valueOf(totalv));
        }
    }//GEN-LAST:event_tblFacturaKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        factura = new Factura();
        factura.setCliente(cliente1);
        factura.setIva(ivav);
        factura.setTotal(totalv);
        factura.setSubtotal(subtotalv);
        factura.setFecha(fecha);
        for(int i =0;i<tblFactura.getRowCount()-1;i++){
            System.out.println(i);
            detalleFactura= new DetalleFactura();
            detalleFactura.setCodigo(Integer.parseInt(tblFactura.getValueAt(i, 0).toString()));
            double cant = Double.parseDouble(tblFactura.getValueAt(i, 1).toString());
            int c=(int) cant;
            detalleFactura.setCosto(c);
            detalleFactura.setProducto(controladorProducto.read(Integer.parseInt(tblFactura.getValueAt(i, 0).toString())));
            detalleFactura.setPrecio(Double.parseDouble(tblFactura.getValueAt(i, 3).toString()));
            detalleFactura.setSubTotal(Double.parseDouble(tblFactura.getValueAt(i, 4).toString()));
            factura.addDetalleFactura(detalleFactura);
        }
        controladorFactura.create(factura);
        JOptionPane.showMessageDialog(this, "factura creada");
        lblCodigo.setText(String.valueOf(controladorFactura.getCodigo()));
        txtCedula.setText("");
        txtDireccion.setText("");
        txtIva.setText("");
        txtNonbre.setText("");
        txtSubTotal.setText("");
        txtTotal.setText("");
        txtTelefono.setText("");
        model.setColumnCount(6);
        model.setRowCount(0);
        Object[] datos2= {"", "", "","0","",""};
        model.addRow(datos2);
        subtotalv=0;
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigos;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechas;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTable tblFactura;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNonbre;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
