/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorFactura;
import ec.ups.edu.modelo.Factura;
import ec.ups.edu.modelo.ImagenTabla;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;



/**
 *
 * @author USER
 */
public class VentanaListarfactura extends javax.swing.JInternalFrame {
private ControladorFactura controladorfactura;
private VentanaBuscarFactura ventanabuscarfactura;
    /**
     * Creates new form VentanaListarfactura
     */
    public VentanaListarfactura(ControladorFactura controladorfactura) {
        initComponents();
         this.controladorfactura=controladorfactura;
            listarFactura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarFactura = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        tblListarFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre Clienete", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListarFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListarFacturaMouseClicked(evt);
            }
        });
        tblListarFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblListarFacturaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblListarFactura);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("LISTAR FACTURA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblListarFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblListarFacturaKeyPressed
        
    }//GEN-LAST:event_tblListarFacturaKeyPressed

    private void tblListarFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListarFacturaMouseClicked
   int tabla=tblListarFactura.getSelectedRow();
        TableModel modelo=tblListarFactura.getModel();
        int codigo = Integer.parseInt(modelo.getValueAt(tabla,0).toString());
        VentanaBuscarFactura ven=new VentanaBuscarFactura(codigo);
        ven.setVisible(true);
        
         
    }
    
public void listarFactura(){
    
    DefaultTableModel modelo= (DefaultTableModel) tblListarFactura.getModel();
    Set<Factura> lista=controladorfactura.getLista();
    for (Factura factura : lista) {
        Object[] datos={
            factura.getCodigo(),
            factura.getCliente().getNombre(),
            factura.getFecha()
        };
        modelo.addRow(datos);
    }
    
    }//GEN-LAST:event_tblListarFacturaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListarFactura;
    // End of variables declaration//GEN-END:variables
}
