/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorCliente;
import ec.ups.edu.modelo.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VentanaCrearCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCrearCliente
     */
    private ControladorCliente controladorCliente;
    public VentanaCrearCliente(ControladorCliente controladorCliente) {
        initComponents();
        this.controladorCliente=controladorCliente;
        txtCodigoCliente.setText(String.valueOf(this.controladorCliente.getCodigo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccionCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnGuardarCliente = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Crear Cliente");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 20, 160, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel3.setText("Codigo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 110, 110, 40);

        txtCodigoCliente.setEditable(false);
        jPanel1.add(txtCodigoCliente);
        txtCodigoCliente.setBounds(190, 102, 220, 40);
        jPanel1.add(txtNombreCliente);
        txtNombreCliente.setBounds(190, 170, 220, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 170, 110, 40);
        jPanel1.add(txtCedulaCliente);
        txtCedulaCliente.setBounds(190, 240, 220, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel5.setText("Cedula:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 240, 110, 40);
        jPanel1.add(txtDireccionCliente);
        txtDireccionCliente.setBounds(190, 300, 220, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel6.setText("Direccion:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 310, 110, 40);
        jPanel1.add(txtEmailCliente);
        txtEmailCliente.setBounds(190, 360, 220, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 360, 110, 40);
        jPanel1.add(txtTelefonoCliente);
        txtTelefonoCliente.setBounds(190, 410, 220, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel8.setText("Telefono:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 420, 110, 40);

        btnGuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/ups/edu/imagenes/guardar.jpg"))); // NOI18N
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarCliente);
        btnGuardarCliente.setBounds(140, 460, 90, 99);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/ups/edu/imagenes/cancelar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(310, 460, 100, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        Cliente cliente=new Cliente();
   
        cliente.setCedula(txtCedulaCliente.getText());
        cliente.setDireccion(txtDireccionCliente.getText());
        cliente.setEmail(txtEmailCliente.getText());
        cliente.setNombre(txtNombreCliente.getText());
        cliente.setTelefono(txtTelefonoCliente.getText());
        controladorCliente.create(cliente);
        JOptionPane.showMessageDialog(this, "cliente creado exitosamente");
        txtCodigoCliente.setText(Integer.toString(this.controladorCliente.getCodigo()));
        txtCedulaCliente.setText("");
        txtDireccionCliente.setText("");
        txtEmailCliente.setText("");
        txtNombreCliente.setText("");
        txtTelefonoCliente.setText("");
        
        
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
