/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorCliente;
import ec.ups.edu.modelo.Cliente;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VentanaCrearCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCrearCliente
     */
    private ControladorCliente controladorCliente;
    private String palabra;
    public VentanaCrearCliente(ControladorCliente controladorCliente) {
        initComponents();
        this.controladorCliente=controladorCliente;
        txtCodigoCliente.setText(String.valueOf(this.controladorCliente.getCodigo()));
    }
    public void cambiaridioma(ResourceBundle mensajes){
        lblCrearCliente.setText(mensajes.getString("CrearCliente"));
        lblCedula.setText(mensajes.getString("CedulaCrearCliente"));
        lblCodigo.setText(mensajes.getString("IngresarCodigo"));
        lblNombre.setText(mensajes.getString("NombreCrearCliente"));
        lblEmail.setText(mensajes.getString("EmailCrearCliente"));
        lblDireccion.setText(mensajes.getString("DireccionCrearCliente"));
        lblTelefono.setText(mensajes.getString("TelefonoCrearCliente"));
        btnGuardarCliente.setText(mensajes.getString("btnGuardar"));
        btnCancelar.setText(mensajes.getString("CancelarCrearCliente"));
        palabra=mensajes.getString("ClienteMensaje");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCrearCliente = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtDireccionCliente = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        btnGuardarCliente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(null);

        lblCrearCliente.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblCrearCliente.setText("Crear Cliente");
        jPanel1.add(lblCrearCliente);
        lblCrearCliente.setBounds(170, 20, 160, 50);

        lblCodigo.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblCodigo.setText("Codigo:");
        jPanel1.add(lblCodigo);
        lblCodigo.setBounds(60, 110, 110, 40);

        txtCodigoCliente.setEditable(false);
        jPanel1.add(txtCodigoCliente);
        txtCodigoCliente.setBounds(190, 102, 220, 40);
        jPanel1.add(txtNombreCliente);
        txtNombreCliente.setBounds(190, 170, 220, 40);

        lblNombre.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre);
        lblNombre.setBounds(60, 170, 110, 40);
        jPanel1.add(txtCedulaCliente);
        txtCedulaCliente.setBounds(190, 240, 220, 40);

        lblCedula.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblCedula.setText("Cedula:");
        jPanel1.add(lblCedula);
        lblCedula.setBounds(60, 240, 110, 40);
        jPanel1.add(txtDireccionCliente);
        txtDireccionCliente.setBounds(190, 300, 220, 40);

        lblDireccion.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblDireccion.setText("Direccion:");
        jPanel1.add(lblDireccion);
        lblDireccion.setBounds(60, 310, 110, 40);
        jPanel1.add(txtEmailCliente);
        txtEmailCliente.setBounds(190, 360, 220, 40);

        lblEmail.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblEmail.setText("Email:");
        jPanel1.add(lblEmail);
        lblEmail.setBounds(60, 360, 110, 40);
        jPanel1.add(txtTelefonoCliente);
        txtTelefonoCliente.setBounds(190, 410, 220, 40);

        lblTelefono.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblTelefono.setText("Telefono:");
        jPanel1.add(lblTelefono);
        lblTelefono.setBounds(60, 420, 110, 40);

        btnGuardarCliente.setText("GUARDAR");
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarCliente);
        btnGuardarCliente.setBounds(140, 470, 90, 40);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(310, 470, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        ResourceBundle mensajes;
        Cliente cliente=new Cliente();
        cliente.setCedula(txtCedulaCliente.getText());
        cliente.setDireccion(txtDireccionCliente.getText());
        cliente.setEmail(txtEmailCliente.getText());
        cliente.setNombre(txtNombreCliente.getText());
        cliente.setTelefono(txtTelefonoCliente.getText());
        controladorCliente.create(cliente);
        JOptionPane.showMessageDialog(this,palabra);
        txtCodigoCliente.setText(Integer.toString(this.controladorCliente.getCodigo()));
        txtCedulaCliente.setText("");
        txtDireccionCliente.setText("");
        txtEmailCliente.setText("");
        txtNombreCliente.setText("");
        txtTelefonoCliente.setText("");
        
        
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCrearCliente;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
