/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorClase;
import ec.ups.edu.modelo.Clase;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VentanaEliminarClase extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaEliminarClase
     */
    ControladorClase controladorClase;
    public VentanaEliminarClase(ControladorClase controladorClase) {
        initComponents();
        this.controladorClase=controladorClase;
        this.setSize(500, 800);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCodigoEliminarClase = new javax.swing.JTextField();
        lblCodigoEliminarClase = new javax.swing.JLabel();
        lblDescripcionEliminarClase = new javax.swing.JLabel();
        txtDescripcionEliminarClase = new javax.swing.JTextField();
        btnBuscarEliminarClase = new javax.swing.JButton();
        btnEliminarEliminarClase = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Eliminar Clases");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(124, 13, 188, 50);
        getContentPane().add(txtCodigoEliminarClase);
        txtCodigoEliminarClase.setBounds(215, 111, 220, 40);

        lblCodigoEliminarClase.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblCodigoEliminarClase.setText("Codigo:");
        getContentPane().add(lblCodigoEliminarClase);
        lblCodigoEliminarClase.setBounds(78, 106, 110, 40);

        lblDescripcionEliminarClase.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblDescripcionEliminarClase.setText("Descripcion:");
        getContentPane().add(lblDescripcionEliminarClase);
        lblDescripcionEliminarClase.setBounds(78, 205, 133, 40);
        getContentPane().add(txtDescripcionEliminarClase);
        txtDescripcionEliminarClase.setBounds(216, 205, 219, 40);

        btnBuscarEliminarClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/ups/edu/imagenes/buscar.png"))); // NOI18N
        btnBuscarEliminarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEliminarClaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarEliminarClase);
        btnBuscarEliminarClase.setBounds(128, 263, 100, 100);

        btnEliminarEliminarClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/ups/edu/imagenes/eliminar.jpg"))); // NOI18N
        btnEliminarEliminarClase.setEnabled(false);
        btnEliminarEliminarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEliminarClaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarEliminarClase);
        btnEliminarEliminarClase.setBounds(274, 263, 100, 90);

        lblNombre.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblNombre.setText("nombre:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(78, 158, 133, 40);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(216, 158, 219, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEliminarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarClaseActionPerformed
      int codigo=Integer.parseInt(txtCodigoEliminarClase.getText());
      Clase clase=controladorClase.read(codigo);
      txtDescripcionEliminarClase.setText(clase.getDescripcion());
      txtNombre.setText(clase.getNombre());
      btnEliminarEliminarClase.setEnabled(true);
    }//GEN-LAST:event_btnBuscarEliminarClaseActionPerformed

    private void btnEliminarEliminarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEliminarClaseActionPerformed
        int codigo=Integer.parseInt(txtCodigoEliminarClase.getText());
        controladorClase.remove(codigo);
        JOptionPane.showMessageDialog(this, "Clase eliminada correctamente");
        txtCodigoEliminarClase.setText("");
        txtDescripcionEliminarClase.setText("");
        txtNombre.setText("");
        
    }//GEN-LAST:event_btnEliminarEliminarClaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEliminarClase;
    private javax.swing.JButton btnEliminarEliminarClase;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCodigoEliminarClase;
    private javax.swing.JLabel lblDescripcionEliminarClase;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtCodigoEliminarClase;
    private javax.swing.JTextField txtDescripcionEliminarClase;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
