/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorCliente;
import ec.ups.edu.modelo.Cliente;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author USER
 */
public class VentanaListarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaListarCliente
     */
    ControladorCliente controladorCliente;
    public VentanaListarCliente(ControladorCliente controladorCliente) {
        initComponents();
        this.controladorCliente=controladorCliente;
        llenarTabla();
    }
    public void cambiaridioma(ResourceBundle mensajes) {
        lblListarCliente.setText(mensajes.getString("ListarCliente"));
        
        JTableHeader th = tblCliente.getTableHeader();
        TableColumnModel tm = th.getColumnModel();
        TableColumn tc;
        tc = tm.getColumn(0);
        tc.setHeaderValue(mensajes.getString("IngresarCodigo"));
        tc=tm.getColumn(1);
        tc.setHeaderValue(mensajes.getString("NombreCrearCliente"));
        tc = tm.getColumn(2);
        tc.setHeaderValue(mensajes.getString("CedulaCrearCliente"));
        tc = tm.getColumn(3);
        tc.setHeaderValue(mensajes.getString("DireccionCrearCliente"));
        tc = tm.getColumn(4);
        tc.setHeaderValue(mensajes.getString("EmailCrearCliente"));
        tc = tm.getColumn(5);
        tc.setHeaderValue(mensajes.getString("TelefonoCrearCliente"));
        th.repaint();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListarCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        setClosable(true);

        lblListarCliente.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblListarCliente.setText("Listar Cliente");

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "CEDULA", "DIRECCION", "EMAIL", "TELEFONO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.setRowHeight(30);
        jScrollPane1.setViewportView(tblCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(lblListarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarTabla(){
        Set<Cliente> lista=controladorCliente.getLista();
        DefaultTableModel modelo= (DefaultTableModel) tblCliente.getModel();
        
        for (Cliente cliente : lista) {
            Object[] datos={
                cliente.getCodigo(),
                cliente.getNombre(),
                cliente.getCedula(),
                cliente.getDireccion(),
                cliente.getEmail(),
                cliente.getTelefono()
            };
            modelo.addRow(datos);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListarCliente;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables
}
